### PR TITLE
Spark 18860 vamp

### PR DESCRIPTION
**Pull request by mallman**
These are some additional changes we made as part of our internal Spark parquet 1.9 upgrade.

### CODE REVIEW

**Comment by mallman** [comment]
Hi @dongjoon-hyun. Sorry I just threw this on you. I should have provided more context.

VideoAmp has been running Spark 2.1 with a slightly modified version of parquet 1.9.0 internally. We made a few additional changes to the Spark codebase, and I want to contribute them for your review.

**Comment by dongjoon-hyun** [comment]
Thank you for sharing the know-how.
BTW, according to the comments on my PR so far, the target will be 1.8.2 instead of 1.9.0.
Let's see the Parquet community's activity.

**Comment by mallman** [comment]
It looks like we're sticking with parquet-mr 1.8 for now. LMK if you'd like me to re-open this PR.

**Comment by dongjoon-hyun** [comment]
Yes. It looks like that.
Anyway, thank you again!

**Pull request closed without merging**
